name: DIGITAL REMOTE DESKTOP

on: [push, workflow_dispatch]

jobs:


  build:
    runs-on: windows-latest
    steps:


    - name: Download Files
      run: 
          Invoke-WebRequest https://raw.githubusercontent.com/Bang-Sahrul-Gunawan-Cyber/RDP-2024/master/start.bat -OutFile start.bat
          Invoke-WebRequest https://raw.githubusercontent.com/Bang-Sahrul-Gunawan-Cyber/RDP-2024/master/wallpaper.bat -OutFile wallpaper.bat
          Invoke-WebRequest https://raw.githubusercontent.com/Bang-Sahrul-Gunawan-Cyber/RDP-2024/master/loop.bat -OutFile loop.bat
      
      
      
    - name: Extract
      run: Expand-Archive ngrok.zip
      
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken 2Nb2ImLGfWMVBmdl67qRNMiVwDp_3yVL5dfBZQUjbBrEkBAhA
      

    - name: Memberikan Data..
    
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0        
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: Make Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
      
    - name: PERMINTAAN CPU DAN RAM
      run: cmd /c start.bat
      
      
    - name: SUKSES TERHUBUNG KE SERVER RDP
      run: cmd /c loop.bat
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
